sudo: required

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt-get install -y make git
- docker pull ubuntu:16.04

script:
- make docker-build
- make unit-test

notifications:
  email: true
  # irc:
  #   channels:
  #     - "chat.freenode.net#thenets-opensource"
  #   on_success: change # default: always
  #   on_failure: always # default: always
  #   use_notice: true